apiVersion: v1
kind: Service
metadata:
  name: onsera-backend
  namespace: onsera
  labels:
    app: onsera-backend
spec:
  type: ClusterIP
  selector:
    app: onsera-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
